package com.invoiceme.domain.invoice;

import com.invoiceme.application.common.UserContext;
import com.invoiceme.application.invoice.dto.CreateInvoiceRequest;
import com.invoiceme.application.invoice.dto.UpdateInvoiceRequest;
import com.invoiceme.domain.common.exceptions.NotFoundException;
import com.invoiceme.domain.common.exceptions.ValidationException;
import com.invoiceme.domain.customer.Customer;
import com.invoiceme.domain.invoice.events.InvoiceCreatedEvent;
import com.invoiceme.domain.invoice.events.InvoiceDeletedEvent;
import com.invoiceme.domain.invoice.events.InvoiceStatusChangedEvent;
import com.invoiceme.infrastructure.persistence.InvoiceRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.springframework.context.ApplicationEventPublisher;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

/**
 * Unit tests for Invoice entity domain logic.
 * These tests focus on pure domain behavior with minimal infrastructure dependencies.
 */
class InvoiceTest {

    private UUID testUserId;
    private InvoiceRepository invoiceRepository;
    private ApplicationEventPublisher eventPublisher;

    @BeforeEach
    void setUp() {
        testUserId = UUID.randomUUID();
        UserContext.setCurrentUser(testUserId);
        invoiceRepository = mock(InvoiceRepository.class);
        eventPublisher = mock(ApplicationEventPublisher.class);
    }

    @AfterEach
    void tearDown() {
        UserContext.clear();
    }

    // === CREATE TESTS ===

    @Test
    void testCreateInvoiceWithAutoGeneratedNumber() {
        // Given
        Customer customer = createTestCustomer();
        CreateInvoiceRequest request = new CreateInvoiceRequest();
        request.setCustomerId(customer.getId());
        request.setNotes("Test invoice notes");

        // Mock repository to return existing invoices for today
        when(invoiceRepository.findInvoiceNumbersByPrefix(anyString()))
            .thenReturn(Arrays.asList("INV-2025-11-09-001", "INV-2025-11-09-002"));
        when(invoiceRepository.existsByInvoiceNumberAndIsDeletedFalse(anyString()))
            .thenReturn(false);

        // When
        Invoice invoice = new Invoice();
        invoice.beforeCreate(request, customer, invoiceRepository);
        invoice.create(request, customer, invoiceRepository);

        // Then
        assertNotNull(invoice.getInvoiceNumber());
        assertTrue(invoice.getInvoiceNumber().startsWith("INV-"));
        assertTrue(invoice.getInvoiceNumber().matches("INV-\\d{4}-\\d{2}-\\d{2}-\\d{3}"));
        assertEquals(customer.getId(), invoice.getCustomerId());
        assertEquals("Test invoice notes", invoice.getNotes());
        assertEquals(InvoiceStatus.DRAFT, invoice.getStatus());
        assertEquals(customer.getCompanyName(), invoice.getCustomerName());
        assertEquals(BigDecimal.ZERO, invoice.getTotal());
        assertEquals(BigDecimal.ZERO, invoice.getAmountPaid());
    }

    @Test
    void testCreateInvoiceWithProvidedNumber() {
        // Given
        Customer customer = createTestCustomer();
        CreateInvoiceRequest request = new CreateInvoiceRequest();
        request.setCustomerId(customer.getId());
        request.setInvoiceNumber("CUSTOM-001");
        request.setNotes("Custom invoice");

        when(invoiceRepository.existsByInvoiceNumberAndIsDeletedFalse("CUSTOM-001"))
            .thenReturn(false);

        // When
        Invoice invoice = new Invoice();
        invoice.beforeCreate(request, customer, invoiceRepository);
        invoice.create(request, customer, invoiceRepository);

        // Then
        assertEquals("CUSTOM-001", invoice.getInvoiceNumber());
        assertEquals(customer.getId(), invoice.getCustomerId());
        assertEquals("Custom invoice", invoice.getNotes());
    }

    @Test
    void testBeforeCreateThrowsExceptionWhenCustomerNull() {
        // Given
        CreateInvoiceRequest request = new CreateInvoiceRequest();
        request.setCustomerId(UUID.randomUUID());

        Invoice invoice = new Invoice();

        // When/Then
        assertThrows(NotFoundException.class, () ->
            invoice.beforeCreate(request, null, invoiceRepository));
    }

    @Test
    void testBeforeCreateThrowsExceptionForDuplicateInvoiceNumber() {
        // Given
        Customer customer = createTestCustomer();
        CreateInvoiceRequest request = new CreateInvoiceRequest();
        request.setCustomerId(customer.getId());
        request.setInvoiceNumber("DUPLICATE-001");

        when(invoiceRepository.existsByInvoiceNumberAndIsDeletedFalse("DUPLICATE-001"))
            .thenReturn(true);

        Invoice invoice = new Invoice();

        // When/Then
        ValidationException exception = assertThrows(ValidationException.class, () ->
            invoice.beforeCreate(request, customer, invoiceRepository));
        assertTrue(exception.getMessage().contains("Invoice number already exists"));
    }

    @Test
    void testAfterCreatePublishesEvent() {
        // Given
        Invoice invoice = new Invoice();
        invoice.setCustomerId(UUID.randomUUID());
        invoice.setStatus(InvoiceStatus.DRAFT);

        // When
        invoice.afterCreate(eventPublisher);

        // Then
        ArgumentCaptor<InvoiceCreatedEvent> eventCaptor = ArgumentCaptor.forClass(InvoiceCreatedEvent.class);
        verify(eventPublisher).publishEvent(eventCaptor.capture());

        InvoiceCreatedEvent event = eventCaptor.getValue();
        assertEquals(invoice.getId(), event.getInvoiceId());
        assertEquals(invoice.getCustomerId(), event.getCustomerId());
        assertEquals(InvoiceStatus.DRAFT, event.getStatus());
    }

    // === UPDATE TESTS ===

    @Test
    void testUpdateDraftInvoice() {
        // Given
        Invoice invoice = new Invoice();
        invoice.setStatus(InvoiceStatus.DRAFT);
        invoice.setInvoiceNumber("INV-001");
        invoice.setNotes("Original notes");

        UpdateInvoiceRequest request = new UpdateInvoiceRequest();
        request.setInvoiceNumber("INV-001-UPDATED");
        request.setNotes("Updated notes");

        when(invoiceRepository.existsByInvoiceNumberAndIsDeletedFalse("INV-001-UPDATED"))
            .thenReturn(false);

        // When
        invoice.beforeUpdate(request, invoiceRepository, false);
        invoice.update(request);

        // Then
        assertEquals("INV-001-UPDATED", invoice.getInvoiceNumber());
        assertEquals("Updated notes", invoice.getNotes());
    }

    @Test
    void testBeforeUpdateThrowsExceptionForNonDraftStatus() {
        // Given
        Invoice invoice = new Invoice();
        invoice.setStatus(InvoiceStatus.SENT);

        UpdateInvoiceRequest request = new UpdateInvoiceRequest();
        request.setInvoiceNumber("NEW-NUMBER");

        // When/Then
        ValidationException exception = assertThrows(ValidationException.class, () ->
            invoice.beforeUpdate(request, invoiceRepository, false));
        assertTrue(exception.getMessage().contains("Cannot edit invoice with status SENT"));
    }

    @Test
    void testBeforeUpdateAllowsSystemUpdateForNonDraftStatus() {
        // Given
        Invoice invoice = new Invoice();
        invoice.setStatus(InvoiceStatus.SENT);
        invoice.setInvoiceNumber("INV-001");

        UpdateInvoiceRequest request = new UpdateInvoiceRequest();
        request.setInvoiceNumber("INV-001");

        // When/Then - Should not throw exception with isSystemUpdate=true
        assertDoesNotThrow(() ->
            invoice.beforeUpdate(request, invoiceRepository, true));
    }

    @Test
    void testBeforeUpdateThrowsExceptionForDuplicateInvoiceNumber() {
        // Given
        Invoice invoice = new Invoice();
        invoice.setStatus(InvoiceStatus.DRAFT);
        invoice.setInvoiceNumber("INV-001");

        UpdateInvoiceRequest request = new UpdateInvoiceRequest();
        request.setInvoiceNumber("DUPLICATE");

        when(invoiceRepository.existsByInvoiceNumberAndIsDeletedFalse("DUPLICATE"))
            .thenReturn(true);

        // When/Then
        ValidationException exception = assertThrows(ValidationException.class, () ->
            invoice.beforeUpdate(request, invoiceRepository, false));
        assertTrue(exception.getMessage().contains("Invoice number already exists"));
    }

    // === MARK AS SENT TESTS ===

    @Test
    void testSendInvoiceSuccess() {
        // Given
        Invoice invoice = new Invoice();
        invoice.setStatus(InvoiceStatus.DRAFT);
        invoice.setTotal(new BigDecimal("100.00"));
        invoice.setCustomerId(UUID.randomUUID());

        // When
        invoice.beforeSend();
        invoice.send();

        // Then
        assertEquals(InvoiceStatus.SENT, invoice.getStatus());
        assertNotNull(invoice.getInvoiceDate());
    }

    @Test
    void testBeforeSendThrowsExceptionWhenNotDraft() {
        // Given
        Invoice invoice = new Invoice();
        invoice.setStatus(InvoiceStatus.SENT);

        // When/Then
        ValidationException exception = assertThrows(ValidationException.class, () ->
            invoice.beforeSend());
        assertTrue(exception.getMessage().contains("Only DRAFT invoices can be sent"));
    }

    @Test
    void testBeforeSendThrowsExceptionWhenTotalIsZero() {
        // Given
        Invoice invoice = new Invoice();
        invoice.setStatus(InvoiceStatus.DRAFT);
        invoice.setTotal(BigDecimal.ZERO);

        // When/Then
        ValidationException exception = assertThrows(ValidationException.class, () ->
            invoice.beforeSend());
        assertTrue(exception.getMessage().contains("Cannot send invoice with total of $0"));
    }

    @Test
    void testAfterSendPublishesEvent() {
        // Given
        Invoice invoice = new Invoice();
        invoice.setCustomerId(UUID.randomUUID());
        invoice.setTotal(new BigDecimal("100.00"));

        // When
        invoice.afterSend(eventPublisher);

        // Then
        ArgumentCaptor<InvoiceStatusChangedEvent> eventCaptor =
            ArgumentCaptor.forClass(InvoiceStatusChangedEvent.class);
        verify(eventPublisher).publishEvent(eventCaptor.capture());

        InvoiceStatusChangedEvent event = eventCaptor.getValue();
        assertEquals(invoice.getId(), event.getInvoiceId());
        assertEquals(invoice.getCustomerId(), event.getCustomerId());
        assertEquals(InvoiceStatus.DRAFT, event.getOldStatus());
        assertEquals(InvoiceStatus.SENT, event.getNewStatus());
        assertEquals(new BigDecimal("100.00"), event.getInvoiceTotal());
    }

    // === DELETE TESTS ===

    @Test
    void testDeleteDraftInvoice() {
        // Given
        Invoice invoice = new Invoice();
        invoice.setStatus(InvoiceStatus.DRAFT);

        // When/Then
        assertDoesNotThrow(() -> invoice.beforeDelete());
        invoice.delete();
        assertTrue(invoice.getIsDeleted());
    }

    @Test
    void testDeletePaidInvoice() {
        // Given
        Invoice invoice = new Invoice();
        invoice.setStatus(InvoiceStatus.PAID);

        // When/Then
        assertDoesNotThrow(() -> invoice.beforeDelete());
        invoice.delete();
        assertTrue(invoice.getIsDeleted());
    }

    @Test
    void testBeforeDeleteThrowsExceptionForSentInvoice() {
        // Given
        Invoice invoice = new Invoice();
        invoice.setStatus(InvoiceStatus.SENT);

        // When/Then
        ValidationException exception = assertThrows(ValidationException.class, () ->
            invoice.beforeDelete());
        assertTrue(exception.getMessage().contains("Cannot delete SENT invoices"));
    }

    @Test
    void testAfterDeletePublishesEvent() {
        // Given
        Invoice invoice = new Invoice();
        invoice.setCustomerId(UUID.randomUUID());
        invoice.setStatus(InvoiceStatus.DRAFT);

        // When
        invoice.afterDelete(eventPublisher);

        // Then
        ArgumentCaptor<InvoiceDeletedEvent> eventCaptor =
            ArgumentCaptor.forClass(InvoiceDeletedEvent.class);
        verify(eventPublisher).publishEvent(eventCaptor.capture());

        InvoiceDeletedEvent event = eventCaptor.getValue();
        assertEquals(invoice.getId(), event.getInvoiceId());
        assertEquals(invoice.getCustomerId(), event.getCustomerId());
        assertEquals(InvoiceStatus.DRAFT, event.getInvoiceStatus());
    }

    // === BALANCE CALCULATION TEST ===

    @Test
    void testGetBalanceCalculation() {
        // Given
        Invoice invoice = new Invoice();
        invoice.setTotal(new BigDecimal("100.00"));
        invoice.setAmountPaid(new BigDecimal("30.00"));

        // When
        BigDecimal balance = invoice.getBalance();

        // Then
        assertEquals(new BigDecimal("70.00"), balance);
    }

    // === Helper Methods ===

    private Customer createTestCustomer() {
        Customer customer = new Customer();
        customer.setId(UUID.randomUUID());
        customer.setCompanyName("Acme Corp");
        customer.setEmail("test@acme.com");
        return customer;
    }
}
